Main page
rskinnerc/vet-appointments-react pull request #11
Opened 2022-09-22 15:48 UTC by mistermaxis

### Tasks Completed:
- Create doctor reducer
- Add reducer to store
- Create Main Page
- Create Nav Menu
- Add style to Main Page and Nav Menu

2022-09-22 18:41 UTC, rskinnerc requested changes
Dear @mistermaxis 

Excellent job so far. I have written some comments below. Please add the required changes.

thank you very much. Keep it up!

2022-09-22 18:41 UTC, rskinnerc commented on src/pages/MainPage.js
> +                    </Link>
Dear @mistermaxis 

Please replace these details with the description field of Doctor as per the original design

![image](https://user-images.githubusercontent.com/26911718/191825738-512fd40b-1aa6-4c0a-900d-99c010efcb29.png)

2022-09-22 18:41 UTC, rskinnerc commented on src/pages/MainPage.test.js
> +    expect(xpr).toHaveLength(5);
Dear @mistermaxis 

I'm getting this error when running the tests. Kindly please double-check where is it coming from:

![image](https://user-images.githubusercontent.com/26911718/191825515-f44cbaed-b442-4719-bc82-5a27779eaa21.png)

2022-09-22 18:41 UTC, rskinnerc commented on src/pages/MainPage.js
> +      <h1 className="text-5xl md:text-6xl font-bold text-center mt-16 md:self-end md:mr-24 md:mt-36">LATEST VETS</h1>
Dear @mistermaxis 

Please add the suggested subtitle as per the original design. It could make our design look better.

![image](https://user-images.githubusercontent.com/26911718/191825996-ffb0eddb-28af-4538-9559-2fdbb99f48e7.png)

2022-09-23 00:41 UTC, mistermaxis commented on src/pages/MainPage.js
> +                    </Link>
Hey  @rskinnerc, thanks for the review. I updated the cards to just show the description and removed the rest of the fields except for the title. :+1:

2022-09-23 00:42 UTC, mistermaxis commented on src/pages/MainPage.test.js
> +    expect(xpr).toHaveLength(5);
Alright. I updated the test and also changed the target since it doesn't show the experience and other fields.

2022-09-23 00:43 UTC, mistermaxis commented on src/pages/MainPage.js
> +      <h1 className="text-5xl md:text-6xl font-bold text-center mt-16 md:self-end md:mr-24 md:mt-36">LATEST VETS</h1>
Done. Let me know what you think. :+1:

2022-09-23 12:55 UTC, rskinnerc approved these changes
Excellent Job @mistermaxis 

You have implemented he changes correctly. You can merge your work into `dev` now.

Thank you

2022-09-23 13:35 UTC, merged